version: "3"

services:
  chirpstack:
    image: chirpstack/chirpstack:4.0.0
    container_name: lora_chirpstack
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - emqx
      - redis
    environment:
      - MQTT_BROKER_HOST=emqx
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - 8081:8080

  # chirpstack-gateway-bridge-eu868:
  #   image: chirpstack/chirpstack-gateway-bridge:4.0.0
  #   ports:
  #     - 1700:1700/udp
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  #   depends_on: 
  #     - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4.0.0
    container_name: lora_chirpstack-rest-api
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack

  postgres:
    image: postgres:14-alpine
    container_name: lora_postgres
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root

  redis:
    image: redis:7-alpine
    container_name: lora_redis
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: lora_mosquitoo
    # ports:
    #   - 1883:1883
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  emqx:
    image: emqx/emqx:5.0.0
    container_name: lora_emqx
    ports:
      - 1883:1883
      - 8083:8083 
      - 8883:8883 
      - 8084:8084 
      - 8082:18083

volumes:
  postgresqldata:
  redisdata:
